---
version: '3'
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - </path/to/config>:/config
      - </path/to/movies>:/music #optional
      - </path/to/downloads>:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped
#    labels:
#      - "com.centurylinklabs.watchtower.enable=true" #optional, enable if using watchtower