---
version: '3'
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=<$PUID>
      - PGID=<$GUID>
      - VERSION=docker
#      - PLEX_CLAIM= #optional, i dont use this personally
    volumes:
      - </path/to/config>:/config
      - </path/to/tv>:/tv
      - </path/to/movies>:/movies
      - </path/to/music>:/music
      - </path/to/audiobooks>:/audiobooks
    restart: unless-stopped
#    labels:
#      - "com.centurylinklabs.watchtower.enable=true" #optional, enable if using watchtower