---
version: '3'
services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000b
      - TZ=America/Los_Angeles
    volumes:
      - </path/to/config>:/config
      - </path/to/movies>:/movies #optional
      - </path/to/downloads>:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
#    labels:
#      - "com.centurylinklabs.watchtower.enable=true" #optional, enable if using watchtower