---
version: '3'
services:
  fail2ban:
    image: lscr.io/linuxserver/fail2ban:latest
    container_name: fail2ban
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Americas/Los_Angeles
    volumes:
      - ./fail2ban/config:/config
      - /var/log:/var/log:ro
#      - /path/to/sonarr/log:/remotelogs/sonarr:ro #optional
#      - /path/to/sonarr/log:/remotelogs/sonarr:ro #optional
    restart: unless-stopped
#    labels:
#      - "com.centurylinklabs.watchtower.enable=true" #optional, enable if using watchtower