---
version: '3'
services:
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - AUTO_UPDATE=true #optional
#      - RUN_OPTS=<run options here> #optional
    volumes:
      - </path/to/config>:/config
      - </path/to/downloads>:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
#    labels:
#      - "com.centurylinklabs.watchtower.enable=true" #optional, enable if using watchtower