  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=<$PUID>
      - PGID=<$GUID>
      - TZ=Americas/Los_Angeles
      - JELLYFIN_PublishedServerUrl=<$local.ip.address> #optional
    volumes:
      - </path/to/config>:/config
      - </path/to/tv>:/data/tvshows
      - </path/to/movies>:/data/movies
      - </path/to/audiobooks>:/data/audiobooks
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
#    labels:
#      - "com.centurylinklabs.watchtower.enable=true" #optional, enable if using watchtower