version: '3'
services:
  wikijs:
    image: lscr.io/linuxserver/wikijs:latest
    container_name: wikijs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Americas/Los_Angeles
    volumes:
      - ./wikijs/config:/config
      - ./wikijs/data:/data
    ports:
      - 3000:3000
    restart: unless-stopped
#    labels:
#      - "com.centurylinklabs.watchtower.enable=true"